const card = document.createElement('div');
const cardBody = document.createElement('div');
const task = document.createElement('input');
const description = document.createElement('text-area');
const date = document.createElement('input');
const addTask = document.createElement('button');
card.id = 'task-form';
card.style.width = '18rem';
card.classList.add('card');
cardBody.classList.add('card-body');
task.classList.add('form-control', 'card-title');
task.placeholder = 'New Task';
task.type = 'text';
task.id = 'task';
description.classList.add('form-control', 'card-text', 'my-1');
description.setAttribute('placeholder', 'Task details');
description.style.height = '60px';
description.id = 'description';
date.classList.add('form-control', 'card-subtitle');
date.placeholder = 'Task details';
date.type = 'date';
date.id = 'date';
addTask.classList.add('btn', 'btn-primary');
addTask.id = 'add-task';
addTask.innerHTML = 'Add Task';
card.appendChild(cardBody);
cardBody.appendChild(task);
cardBody.appendChild(date);
cardBody.appendChild(description);
cardBody.appendChild(addTask);

export default card;
